[build]
builder = "nixpacks"

[deploy]
startCommand = "FLASK_APP=run.py python -m flask db upgrade && gunicorn run:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
