"""Add activity_logs table

Revision ID: 188c95ba1fed
Revises: d614fe4a6e98
Create Date: 2026-03-13 20:47:30.800285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188c95ba1fed'
down_revision = 'd614fe4a6e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_username', sa.String(length=80), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_actor_username'), ['actor_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ump_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_reviewing_officer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_controlling_officer'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['controlling_officer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewing_officer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_controlling_officer'), 'users', ['controlling_officer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_users_reviewing_officer'), 'users', ['reviewing_officer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ump_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_actor_username'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action_type'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
