"""Add CSC workflow tables

Revision ID: 33b1d640498b
Revises: ab12cd34ef56
Create Date: 2026-03-17 15:35:15.902302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b1d640498b'
down_revision = 'ab12cd34ef56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csc_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('spec_number', sa.String(length=100), nullable=False),
    sa.Column('chemical_name', sa.String(length=255), nullable=False),
    sa.Column('committee_name', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.String(length=50), nullable=True),
    sa.Column('prepared_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_role', sa.String(length=20), nullable=False),
    sa.Column('is_admin_draft', sa.Boolean(), nullable=False),
    sa.Column('phase1_locked', sa.Boolean(), nullable=False),
    sa.Column('parent_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_stage', sa.String(length=50), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_draft_id'], ['csc_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csc_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_csc_drafts_admin_stage', ['admin_stage'], unique=False)
        batch_op.create_index('ix_csc_drafts_spec_number', ['spec_number'], unique=False)
        batch_op.create_index('ix_csc_drafts_status', ['status'], unique=False)

    op.create_table('csc_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csc_audit', schema=None) as batch_op:
        batch_op.create_index('ix_csc_audit_action_time', ['action_time'], unique=False)
        batch_op.create_index('ix_csc_audit_draft_id', ['draft_id'], unique=False)

    op.create_table('csc_impact_analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('operational_impact_score', sa.Integer(), nullable=False),
    sa.Column('safety_environment_score', sa.Integer(), nullable=False),
    sa.Column('supply_risk_score', sa.Integer(), nullable=False),
    sa.Column('no_substitute_flag', sa.Boolean(), nullable=False),
    sa.Column('impact_score_total', sa.Float(), nullable=False),
    sa.Column('impact_grade', sa.String(length=20), nullable=False),
    sa.Column('operational_note', sa.Text(), nullable=True),
    sa.Column('safety_environment_note', sa.Text(), nullable=True),
    sa.Column('supply_risk_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id')
    )
    op.create_table('csc_issue_flags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csc_issue_flags', schema=None) as batch_op:
        batch_op.create_index('ix_csc_issue_flags_draft_sort', ['draft_id', 'sort_order'], unique=False)

    op.create_table('csc_parameters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter_name', sa.String(length=500), nullable=False),
    sa.Column('parameter_type', sa.String(length=50), nullable=False),
    sa.Column('existing_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('test_method', sa.Text(), nullable=True),
    sa.Column('test_procedure_type', sa.String(length=100), nullable=False),
    sa.Column('test_procedure_text', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csc_parameters', schema=None) as batch_op:
        batch_op.create_index('ix_csc_parameters_draft_sort', ['draft_id', 'sort_order'], unique=False)

    op.create_table('csc_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_draft_id', sa.BigInteger(), nullable=False),
    sa.Column('child_draft_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_draft_id')
    )
    op.create_table('csc_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'section_name', name='uq_csc_sections_draft_name')
    )
    with op.batch_alter_table('csc_sections', schema=None) as batch_op:
        batch_op.create_index('ix_csc_sections_draft_sort', ['draft_id', 'sort_order'], unique=False)

    op.create_table('csc_spec_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('source_action', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['csc_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'spec_version', name='uq_csc_spec_versions_draft_version')
    )
    with op.batch_alter_table('csc_spec_versions', schema=None) as batch_op:
        batch_op.create_index('ix_csc_spec_versions_draft_version', ['draft_id', 'spec_version'], unique=False)

    with op.batch_alter_table('material_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_master_group'))
        batch_op.drop_index(batch_op.f('ix_material_master_material_type'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_master_material_type'), ['material_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_master_group'), ['group'], unique=False)

    with op.batch_alter_table('csc_spec_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_spec_versions_draft_version')

    op.drop_table('csc_spec_versions')
    with op.batch_alter_table('csc_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_sections_draft_sort')

    op.drop_table('csc_sections')
    op.drop_table('csc_revisions')
    with op.batch_alter_table('csc_parameters', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_parameters_draft_sort')

    op.drop_table('csc_parameters')
    with op.batch_alter_table('csc_issue_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_issue_flags_draft_sort')

    op.drop_table('csc_issue_flags')
    op.drop_table('csc_impact_analysis')
    with op.batch_alter_table('csc_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_audit_draft_id')
        batch_op.drop_index('ix_csc_audit_action_time')

    op.drop_table('csc_audit')
    with op.batch_alter_table('csc_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_csc_drafts_status')
        batch_op.drop_index('ix_csc_drafts_spec_number')
        batch_op.drop_index('ix_csc_drafts_admin_stage')

    op.drop_table('csc_drafts')
    # ### end Alembic commands ###
