"""add Inventory Monitoring tables without retiring legacy inventory data

Revision ID: b4d5e6f7a8b
Revises: 8c9d0e1f2a3b
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "b4d5e6f7a8b"
down_revision = "8c9d0e1f2a3b"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("inventory_monitoring_upload_batches",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("source_group", sa.String(16), nullable=False), sa.Column("reporting_date", sa.Date()), sa.Column("source_filename", sa.String(255), nullable=False), sa.Column("source_content_type", sa.String(120), nullable=False), sa.Column("source_checksum", sa.String(64), nullable=False), sa.Column("source_file_size", sa.BigInteger(), nullable=False), sa.Column("source_data", mysql.LONGBLOB(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("is_superseded", sa.Boolean(), nullable=False), sa.Column("superseded_by_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_upload_batches.id", ondelete="SET NULL")), sa.Column("row_count", sa.Integer(), nullable=False), sa.Column("accepted_count", sa.Integer(), nullable=False), sa.Column("rejected_count", sa.Integer(), nullable=False), sa.Column("duplicate_count", sa.Integer(), nullable=False), sa.Column("warnings_json", sa.Text(), nullable=False), sa.Column("validation_json", sa.Text(), nullable=False), sa.Column("uploaded_by", sa.BigInteger(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("uploaded_at", sa.DateTime(), nullable=False))
    op.create_index("ix_inventory_monitoring_batches_period", "inventory_monitoring_upload_batches", ["source_group", "reporting_date"]); op.create_index("ix_inventory_monitoring_batches_status", "inventory_monitoring_upload_batches", ["status"]); op.create_index("ix_inventory_monitoring_batches_uploaded_at", "inventory_monitoring_upload_batches", ["uploaded_at"])
    op.create_table("inventory_monitoring_snapshots", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("reporting_date", sa.Date(), nullable=False), sa.Column("material_group", sa.String(2), nullable=False), sa.Column("batch_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_upload_batches.id", ondelete="CASCADE"), nullable=False), sa.Column("is_published", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("reporting_date", "material_group", "batch_id", name="uq_inventory_monitoring_snapshot_batch")); op.create_index("ix_inventory_monitoring_snapshots_date_group", "inventory_monitoring_snapshots", ["reporting_date", "material_group"])
    op.create_table("inventory_monitoring_work_centers", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("normalized_name", sa.String(255), nullable=False), sa.Column("zone", sa.String(120)), sa.Column("work_center_type", sa.String(80)), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("normalized_name", name="uq_inventory_monitoring_work_center_name"))
    op.create_table("inventory_monitoring_materials", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("material_code", sa.String(64), nullable=False), sa.Column("description", sa.String(500)), sa.Column("material_group", sa.String(2)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("material_code", name="uq_inventory_monitoring_material_code"))
    op.create_table("inventory_monitoring_work_center_materials", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("work_center_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_work_centers.id", ondelete="CASCADE"), nullable=False), sa.Column("material_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_materials.id", ondelete="CASCADE"), nullable=False), sa.Column("mapping_batch_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_upload_batches.id", ondelete="CASCADE"), nullable=False), sa.Column("is_current", sa.Boolean(), nullable=False), sa.UniqueConstraint("work_center_id", "material_id", "mapping_batch_id", name="uq_inventory_monitoring_mapping_version")); op.create_index("ix_inventory_monitoring_mapping_material", "inventory_monitoring_work_center_materials", ["material_id"])
    op.create_table("inventory_monitoring_records", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("snapshot_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_snapshots.id", ondelete="CASCADE"), nullable=False), sa.Column("batch_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_upload_batches.id", ondelete="CASCADE"), nullable=False), sa.Column("material_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_materials.id", ondelete="SET NULL")), sa.Column("work_center_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_work_centers.id", ondelete="SET NULL")), sa.Column("material_group", sa.String(2), nullable=False), sa.Column("material_code", sa.String(64), nullable=False), sa.Column("material_description", sa.String(500)), sa.Column("work_center_name", sa.String(255), nullable=False), sa.Column("stock_qty", sa.Numeric(20,3)), sa.Column("uom", sa.String(32)), sa.Column("inventory_value_inr", sa.Numeric(20,2)), sa.Column("open_po", sa.Numeric(20,3)), sa.Column("open_pr", sa.Numeric(20,3)), sa.Column("stock_months", sa.Numeric(12,2)), sa.Column("source_sheet", sa.String(255), nullable=False), sa.Column("source_row", sa.Integer(), nullable=False));
    for index, columns in (("ix_inventory_monitoring_records_snapshot", ["snapshot_id"]), ("ix_inventory_monitoring_records_work_center", ["work_center_id"]), ("ix_inventory_monitoring_records_material", ["material_id"]), ("ix_inventory_monitoring_records_group", ["material_group"])): op.create_index(index, "inventory_monitoring_records", columns)
    op.create_table("inventory_monitoring_exceptions", sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True), sa.Column("snapshot_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_snapshots.id", ondelete="CASCADE"), nullable=False), sa.Column("record_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_records.id", ondelete="CASCADE")), sa.Column("work_center_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_work_centers.id", ondelete="SET NULL")), sa.Column("material_id", sa.BigInteger(), sa.ForeignKey("inventory_monitoring_materials.id", ondelete="SET NULL")), sa.Column("exception_type", sa.String(80), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("details", sa.Text()), sa.Column("inventory_value_inr", sa.Numeric(20,2)), sa.Column("stock_months", sa.Numeric(12,2)), sa.Column("created_at", sa.DateTime(), nullable=False));
    for index, columns in (("ix_inventory_monitoring_exceptions_snapshot", ["snapshot_id"]), ("ix_inventory_monitoring_exceptions_type", ["exception_type"]), ("ix_inventory_monitoring_exceptions_work_center", ["work_center_id"])): op.create_index(index, "inventory_monitoring_exceptions", columns)
    op.create_table("inventory_monitoring_thresholds", sa.Column("key", sa.String(64), primary_key=True), sa.Column("value", sa.Numeric(12,2), nullable=False), sa.Column("updated_by", sa.BigInteger(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("updated_at", sa.DateTime(), nullable=False))


def downgrade():
    # This only removes the new monitoring schema. It never drops legacy inventory tables.
    for table in ("inventory_monitoring_thresholds", "inventory_monitoring_exceptions", "inventory_monitoring_records", "inventory_monitoring_work_center_materials", "inventory_monitoring_materials", "inventory_monitoring_work_centers", "inventory_monitoring_snapshots", "inventory_monitoring_upload_batches"):
        op.drop_table(table)
