"""Add CSCConfig and CSCOfficeOrderFile models

Revision ID: ee4884ed2952
Revises: 5e4f6a7b8c9d
Create Date: 2026-03-18 12:30:50.547454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4884ed2952'
down_revision = '5e4f6a7b8c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csc_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directory_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csc_office_order_files',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_data', sa.LargeBinary(length=4294967295), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('csc_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csc_drafts_material_code'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csc_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csc_drafts_material_code'), ['material_code'], unique=False)

    op.drop_table('csc_office_order_files')
    op.drop_table('csc_config')
    # ### end Alembic commands ###
